name: Deploy Fullstack UAS (Lokal)

on:
  push:
    branches: [ "uas-k8s" ]

jobs:
  deploy-fullstack:
    runs-on: self-hosted
    
    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4

    - name: 2. Login ke Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 3. Build & Push Backend
      run: |
        echo "Membangun Backend..." 
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sayur-backend:latest ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/sayur-backend:latest

    - name: 4. Build & Push Frontend
      run: |
        echo "Membangun Frontend..."
        docker build --build-arg REACT_APP_API_URL=http://localhost:5000/ -t ${{ secrets.DOCKERHUB_USERNAME }}/sayur-frontend:latest ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/sayur-frontend:latest

    - name: 5. Update Kubernetes
      run: |
        echo "Deploying to Local Kubernetes..."
        kubectl apply -f k8s/
        kubectl rollout restart deployment/backend
        kubectl rollout restart deployment/frontend
        echo "Selesai! Web & API sudah terupdate."